name: CD Staging

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to PROD
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1